- name: git log
  hosts: runbot_all
  tasks:
  - name: show runbot git head
    become: True
    become_user: odoo
    command: git log --pretty=format:"%d -- %h -- %an --%s" -n 1
    register: gitlog
    args:
        chdir: /home/odoo/runbot/runbot
  - debug: msg="{{ gitlog.stdout }}"

