- name: git log
  hosts: runbot-all
  tasks:
  - name: show runbot git head
    become: True
    become_user: odoo
    command: git log --oneline -n 2
    register: gitlog
    args:
        chdir: /home/odoo/runbot/runbot
  - debug: msg="{{ gitlog.stdout }}"

