---
- name: Stop runbot
  hosts: runbot_all
  tasks:
    - name: stop runbot service
      systemd:
        name: runbot
        state: stopped

- name: Stop Runbot Leader
  hosts: runbot_master
  tasks:
    - name: stop runbot leader service
      systemd:
        name: runbot-leader
        state: stopped
- name: Stop Runbot Frontent
  hosts: runbot_master
  tasks:
    - name: stop runbot runbot service
      systemd:
        name: runbot
        state: stopped
